# Generated by Django 3.2.6 on 2021-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurants', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('dishes', models.CharField(max_length=100)),
                ('dishes_name', models.CharField(max_length=100)),
                ('dishes_price', models.CharField(max_length=100)),
                ('restaurants_in_which_dishes_are_avilable', models.CharField(max_length=100)),
                ('orderplaced', models.CharField(max_length=100)),
                ('user_who_placed_order', models.CharField(max_length=100)),
                ('restaurant_from_which_order_is_placed', models.CharField(max_length=100)),
                ('dishes_which_is_order', models.CharField(max_length=100)),
                ('total_price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
