# Generated by Django 3.2.6 on 2021-08-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dishes', models.CharField(max_length=200)),
                ('sold', models.CharField(max_length=200)),
            ],
        ),
    ]
