# Generated by Django 3.2.6 on 2021-08-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='sold',
            new_name='nosold',
        ),
    ]
